ITERATION_LEARNING = 15000
LEARNING_RATE = 0.1

PROBABILITY_EXPLORE_FOR_AGENTOPTION = 0.0 # useless with OptionExploreQ
PROBABILITY_EXPLORE_IN_OPTION = 0.0
PROBABILITY_EXPLORE_FOR_QAGENT = 0.1

# ZONE_SIZE_X = 4
# ZONE_SIZE_Y = 4
NUMBER_GRAY_COLORS = 0

REWARD_END_OPTION = 10
PENALTY_END_OPTION = - 10
PENALTY_OPTION_ACTION = - 1

PENALTY_ACTION = - 1
PENALTY_AGENT_ACTION = 0
REWARD_KEY = 100
REWARD_DOOR = 100

NUMBER_ACTIONS = 4
ENV_NAME = 'GE_MazeOptions-v1'

NUMBER_SEEDS = 1
