ITERATION_LEARNING = 100000
LEARNING_RATE = 0.1

PROBABILITY_EXPLORE_FOR_AGENTOPTION = 0.0 # useless with OptionExploreQ
PROBABILITY_EXPLORE_IN_OPTION = 0.1
PROBABILITY_EXPLORE_FOR_QAGENT = 0.1

# Zones setting
NUMBER_ZONES_MONTEZUMA_X = (2**5)*5
NUMBER_ZONES_MONTEZUMA_Y = 2*3*5*7

NUMBER_ZONES_X = 2**4
NUMBER_ZONES_Y = 2*5
ZONE_SIZE_X = NUMBER_ZONES_MONTEZUMA_X // NUMBER_ZONES_X #160 Montezuma
ZONE_SIZE_Y = NUMBER_ZONES_MONTEZUMA_Y // NUMBER_ZONES_Y #210 Montezuma (130 with cut-off)
NUMBER_ZONES_MASTER_X = 2**2
NUMBER_ZONES_MASTER_Y = 2*5
ZONE_SIZE_MASTER_X = NUMBER_ZONES_X // NUMBER_ZONES_MASTER_X #160 Montezuma
ZONE_SIZE_MASTER_Y = NUMBER_ZONES_Y // NUMBER_ZONES_MASTER_Y #210 Montezuma (130 with cut-off)
BLURRED = True
GRAY_SCALE = True
NUMBER_GRAY_COLORS = 3

REWARD_END_OPTION = 1000
PENALTY_END_OPTION = - 1000
PENALTY_OPTION_ACTION = - 1

PENALTY_ACTION = - 1
PENALTY_LOST_LIFE = - 1000
PENALTY_AGENT_ACTION = 0 # should stay 0 for the moment

REWARD_KEY = 1000
REWARD_DOOR = 1000

NUMBER_ACTIONS = 4

#ENV_NAME = 'GE_MazeOptions-v1'
ENV_NAME = 'MontezumaRevenge-v0'
#ENV_NAME = 'Pong-v0'

NUMBER_SEEDS = 1
