ITERATION_LEARNING = 10000
LEARNING_RATE = 0.1

PROBABILITY_EXPLORE_FOR_AGENTOPTION = 0.5
PROBABILITY_EXPLORE_IN_OPTION = 0.1
PROBABILITY_EXPLORE_FOR_QAGENT = 0.1

ZONE_SIZE_X = 21 #40 #160 Montezuma
ZONE_SIZE_Y = 21 #105 #210 Montezuma
BLURRED = True
GRAY_SCALE = True
NUMBER_GRAY_COLORS = 50

REWARD_END_OPTION = 0.001
PENALTY_END_OPTION = - 1
PENALTY_ACTION = - 0.01
PENALTY_LOST_LIFE = - 1
PENALTY_AGENT_ACTION = 0
PENALTY_AGENTOPTION_ACTION_OPTION = -0.01
REWARD_AGENTOPTION_ACTION_EXPLORE = 0.01
PENALTY_OPTION_ACTION = - 0.01
REWARD_KEY = 1

NUMBER_ACTIONS = 4
ENV_NAME = 'GE_MazeOptions-v1'
#ENV_NAME = 'MontezumaRevenge-v0'
#ENV_NAME = 'Pong-v0'

NUMBER_SEEDS = 1


